from .categoria_model import CategoriaModel
from .legajo_model import LegajoModel
from .modalidad_liquidacion import ModalidadLiquidacionModel
from .legajo_concepto_model import LegajoConceptoModel
from .conceptos_model import ConceptoModel