from enum import Enum

class EntidadAuditoriaEnum(str, Enum):
    USUARIO = "USUARIO"
    ROL = "ROL"
    PERMISO = "PERMISO"

    LEGAJO = "LEGAJO"
    LEGAJO_CONCEPTO = "LEGAJO_CONCEPTO"
    LEGAJO_NOVEDAD = "LEGAJO_NOVEDAD"

    CONCEPTO = "CONCEPTO"
    CATEGORIA = "CATEGORIA"
    MODALIDAD_LIQUIDACION = "MODALIDAD_LIQUIDACION"

    DATOS_FIJOS_LIQUIDACION = "DATOS_FIJOS_LIQUIDACION"

    PRELIQUIDACION = "PRELIQUIDACION"
    LIQUIDACION = "LIQUIDACION"
    LIQUIDACION_DETALLE = "LIQUIDACION_DETALLE"

    PAGO = "PAGO"
    RECIBO = "RECIBO"
